/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;
//import Evento ;
import Logica.Gasto;
import Ui.Evento;
import Logica.*;
import java.io.File;
import java.io.FileWriter;
import javax.swing.JOptionPane;
/**
 *
 * @author facundo
 */
public class NuevoGasto extends javax.swing.JFrame {
        Gasto Gastos[] = new Gasto[100];
        int cont=0;
        
    /**
     * Creates new form NuevoGasto
     */

   


    public NuevoGasto() {
        initComponents();

        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        lbNombreGasto = new javax.swing.JLabel();
        lbPrecioGasto = new javax.swing.JLabel();
        cxbTotal = new javax.swing.JCheckBox();
        cxbUnidad = new javax.swing.JCheckBox();
        txbNombreGasto = new javax.swing.JTextField();
        txbPrecioGasto = new javax.swing.JTextField();
        btCrearGasto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbCantInvitados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbNombreGasto.setText("cual es el  gasto:");

        lbPrecioGasto.setText("precio de el  gasto:");

        cxbTotal.setText("total de gasto");
        cxbTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxbTotalActionPerformed(evt);
            }
        });

        cxbUnidad.setText("por unidad");

        btCrearGasto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ui/save-icon.png"))); // NOI18N
        btCrearGasto.setText("crear");
        btCrearGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearGastoActionPerformed(evt);
            }
        });

        jLabel3.setText(" invitados");

        lbCantInvitados.setText("  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txbNombreGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbNombreGasto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbPrecioGasto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txbPrecioGasto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbCantInvitados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cxbTotal))
                        .addContainerGap(257, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cxbUnidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCrearGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cxbTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btCrearGasto)
                            .addComponent(cxbUnidad, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lbCantInvitados)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNombreGasto)
                            .addComponent(lbPrecioGasto))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txbNombreGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txbPrecioGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxbTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxbTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxbTotalActionPerformed

    private void btCrearGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearGastoActionPerformed
        Gasto newGasto = new Gasto();
        try{
        int precioGastofinal = 0;
        String nombreGasto = txbNombreGasto.getText();
        newGasto.setNombreGasto(nombreGasto);
        int precioGasto = Integer.parseInt(txbPrecioGasto.getText());
        newGasto.setPrecioGasto(precioGasto);
        int invitados = Integer.parseInt(lbCantInvitados.getText());
        String gastoCreado="";
        if (cont <100){
            Gastos[cont] = newGasto; }
            cont++;
        if (cxbTotal.isSelected()){
            precioGastofinal = precioGasto;
            gastoCreado = nombreGasto +" por $ "+ precioGastofinal;
            newGasto.setTotal(precioGastofinal);} 


        if (cxbUnidad.isSelected()){
            precioGastofinal = precioGasto*invitados;
            gastoCreado = nombreGasto+" por $ "+precioGastofinal;
            newGasto.setTotal(precioGastofinal);}

        if (abstracta.addGasto(newGasto)) {
            JOptionPane.showMessageDialog(this, "gasto guardado");}
 
        System.out.print(Gastos);
        abstracta.refreshTable();
        dispose();
                }
         catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar gasto , Verifique que todos los datos esten cargados");
            System.out.println("Error al guardar");
            }

        try{
        File archivo=new File(abstracta.getNombreEvento()+".txt");
        FileWriter escribir = new FileWriter(archivo, true);
                if (newGasto!= null) {
                    String gasto = newGasto.toString()+"\n";
                    escribir.write(gasto);
                }

            escribir.close();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar  gasto");
            System.out.println("Error al guardar");
        }

        abstracta.refreshTable();
    }//GEN-LAST:event_btCrearGastoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoGasto().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCrearGasto;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox cxbTotal;
    private javax.swing.JCheckBox cxbUnidad;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel lbCantInvitados;
    private javax.swing.JLabel lbNombreGasto;
    private javax.swing.JLabel lbPrecioGasto;
    private javax.swing.JTextField txbNombreGasto;
    private javax.swing.JTextField txbPrecioGasto;
    // End of variables declaration//GEN-END:variables
}
